name: Python CI
on:
  pull_request:
    branches: [ main ]
  merge_group:
    types: [ checks_requested ]

jobs:
  trigger-circleci:
    name: Signal CircleCI to Start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger CircleCI API
        run: |
          # The Merge Queue creates a branch like 'gh-readonly-queue/main/pr-123-...'
          #BRANCH_NAME="${{ github.event.merge_group.head_ref || github.head_ref || github.ref_name }}"
          
          echo "Triggering CircleCI for branch: $BRANCH_NAME"
          
          #RESPONSE=$(curl -X POST https://circleci.com/api/v2/project/github/${{ github.repository }}/pipeline \
          #  -H "Content-Type: application/json" \
          #  -H "Circle-Token: ${{ secrets.CIRCLE_TOKEN }}" \
          #  -d "{ \"branch\": \"$BRANCH_NAME\" }")
          
          #echo "CircleCI Response: $RESPONSE
